defaults:
  - backend: internvl3
  - stage: stage1
  - stage1_datasets: default
  - stage2_datasets: default
  - override hydra/job_logging: disabled
  - _self_

hydra:
  output_subdir: null
  run:
    dir: .
  job:
    chdir: false

data_root: /data/datasets
output_dir: models
wandb_run_name: null
wandb_log_interval: 300
wandb_gradient_log_interval: 1
experiment_name: null
pbar_enabled: false
pbar_api_url: "https://pbar.io/api"
pbar_update_interval: 0.5
num_workers: 16
stage1_max_steps: null
