apiVersion: batch/v1
kind: Job
metadata:
  generateName: reinspection-motivation-plot-
  namespace: eidf098ns
  labels:
    kueue.x-k8s.io/queue-name: eidf098ns-user-queue
spec:
  ttlSecondsAfterFinished: 3600
  parallelism: 1
  completions: 1
  backoffLimit: 0
  template:
    metadata:
      name: reinspection-motivation-plot
    spec:
      containers:
      - name: reinspection-motivation-plot
        image: stogian/l_reinspection:latest
        workingDir: /data/users/stogian/learnable-reinspection
        command:
          - bash
          - -c
          - |
            python -m src.plot_motivation --output_dir outputs/motivation/figures
        imagePullPolicy: "Always"
        env:
          - name: HF_HOME
            value: "/data/Huggingface"
        resources:
          requests:
            cpu: 2
            memory: "4Gi"
          limits:
            cpu: 2
            memory: "4Gi"
        volumeMounts:
          - mountPath: /data
            name: nfs
      restartPolicy: Never
      securityContext:
        runAsUser: 30545
        runAsGroup: 4451
        runAsNonRoot: true
      volumes:
      - name: nfs
        nfs:
          server: 10.24.6.66
          path: /
